import {
  FRENCH_ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL,
  FRENCH_CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL,
  FRENCH_CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL,
  FRENCH_CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL,
  FRENCH_HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL,
  FRENCH_LANGUAGE_NOT_VALID_EXPRESSION_ERROR_MESSAGE,
  FRENCH_THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL,
} from "../constants/screens/home_screen_constants";
import LanguageAbstraction from "./language_abstraction";

class FrenchLanguage extends LanguageAbstraction {
  public ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL: string =
    FRENCH_ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL: string =
    FRENCH_CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL;

  public HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL: string =
    FRENCH_HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL(
    character: string,
  ): string {
    return FRENCH_CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL(
      character,
    );
  }

  public THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL: string =
    FRENCH_THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL(
    value: string,
  ): string {
    return FRENCH_CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL(value);
  }

  public NOT_VALID_EXPRESSION_ERROR_MESSAGE: string =
    FRENCH_LANGUAGE_NOT_VALID_EXPRESSION_ERROR_MESSAGE;
}

export default FrenchLanguage;
