import {
  GERMAN_ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL,
  GERMAN_CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL,
  GERMAN_CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL,
  GERMAN_CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL,
  GERMAN_HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL,
  GERMAN_LANGUAGE_NOT_VALID_EXPRESSION_ERROR_MESSAGE,
  GERMAN_THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL,
} from "../constants/screens/home_screen_constants";
import LanguageAbstraction from "./language_abstraction";

class GermanLanguage extends LanguageAbstraction {
  public ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL: string =
    GERMAN_ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL: string =
    GERMAN_CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL;

  public HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL: string =
    GERMAN_HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL(
    character: string,
  ): string {
    return GERMAN_CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL(
      character,
    );
  }

  public THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL: string =
    GERMAN_THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL(
    value: string,
  ): string {
    return GERMAN_CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL(value);
  }

  public NOT_VALID_EXPRESSION_ERROR_MESSAGE: string =
    GERMAN_LANGUAGE_NOT_VALID_EXPRESSION_ERROR_MESSAGE;
}

export default GermanLanguage;
