import {
  PORTUGUESE_ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL,
  PORTUGUESE_CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL,
  PORTUGUESE_CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL,
  PORTUGUESE_CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL,
  PORTUGUESE_HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL,
  PORTUGUESE_LANGUAGE_NOT_VALID_EXPRESSION_ERROR_MESSAGE,
  PORTUGUESE_THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL,
} from "../constants/screens/home_screen_constants";
import LanguageAbstraction from "./language_abstraction";

class PortugueseLanguage extends LanguageAbstraction {
  public ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL: string =
    PORTUGUESE_ACTION_BAR_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL: string =
    PORTUGUESE_CALCULATOR_KEYBOARD_ELEMENT_ACCESSIBILITY_LABEL;

  public HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL: string =
    PORTUGUESE_HOME_SCREEN_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL(
    character: string,
  ): string {
    return PORTUGUESE_CALCULATOR_KEYBOARD_BUTTON_ELEMENT_ACCESSIBILITY_LABEL(
      character,
    );
  }

  public THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL: string =
    PORTUGUESE_THEME_TOGGLE_BUTTON_ELEMENT_ACCESSIBILITY_LABEL;

  public CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL(
    value: string,
  ): string {
    return PORTUGUESE_CALCULATOR_VIEWFINDER_ELEMENT_ACCESSIBILITY_LABEL(value);
  }

  public NOT_VALID_EXPRESSION_ERROR_MESSAGE: string =
    PORTUGUESE_LANGUAGE_NOT_VALID_EXPRESSION_ERROR_MESSAGE;
}

export default PortugueseLanguage;
