export const EXTRA_SMALL_CALCULATOR_BUTTON_CHARACTER_FONT_SIZE: number = 16;

export const GREATER_CALCULATOR_BUTTON_CHARACTER_FONT_SIZE: number = 42;

export const EXTRA_SMALL_CALCULATOR_VIEWFINDER_CHARACTER_FONT_SIZE: number = 32;

export const GREATER_CALCULATOR_VIEWFINDER_CHARACTER_FONT_SIZE: number = 64;

export const EXTRA_SMALL_CALCULATOR_VIEWFINDER_MARGIN_BOTTOM: number = 16;

export const GREATER_CALCULATOR_VIEWFINDER_MARGIN_BOTTOM: number = 32;

export const EXTRA_SMALL_CALCULATOR_KEYBOARD_PADDING_BOTTOM: number = 8;

export const GREATER_CALCULATOR_KEYBOARD_PADDING_BOTTOM: number = 16;

export const EXTRA_SMALL_CALCULATOR_VIEWFINDER_PADDING_BOTTOM: number = 8;

export const GREATER_CALCULATOR_VIEWFINDER_PADDING_BOTTOM: number = 16;
